### ISSUE TITLE
Build a web front end

### ISSUE THREAD

**Issue by cswbrian** [g0vhk-io/HKAddressParser#1]
Let's build a web front end
The front end should include 3 main 

1. User input address, then return the structured address from OGCIO ALS
2. Support Bulk parsing, user upload/paste txt, then return batch result
3. Display the level of the result, eg (九龍九龍城打鼓嶺道> street level), (九龍九龍城打鼓嶺道68號同豐樓> building level)

Reference: https://parserator.datamade.us/usaddress

**Comment by howawong** [comment]
Complete #5 before #1. We may break down #1 into multiple issues.
