### ISSUE TITLE
Let's structure the project

### ISSUE THREAD

**Issue by cswbrian** [g0vhk-io/HKAddressParser#25]
The project is in a little bit mess, let's orgainse it as the following example, state the dependencies and define the classes:

README.md
DISCUSSION.md
LICENSE
setup.py
requirements.txt
sample/__init__.py
sample/core.py
sample/helpers.py
docs/conf.py
docs/index.rst
tests/test_basic.py
tests/test_advanced.py

**Comment by nandiheath** [comment]
this is done at #40
