### ISSUE TITLE
better to have a pin on the map

### ISSUE THREAD

**Issue by nandiheath** [g0vhk-io/HKAddressParser#26]
after researching the results the map now can show the best match at the map.
however shall we have a pin on the exact location of the map?

**Comment by cswbrian** [comment]
do you mean after the result is displayed, there's a pin corresponding to the suggested coordinate on the map?

**Comment by cswbrian** [comment]
Yes.

**Comment by ylchan87** [comment]
#50 should fix this

**Comment by ylchan87** [comment]
forgot to include some asset in last pull request i.e. #50
#51 should be the correct pull request that fix this
