### ISSUE TITLE
Parse only 5 address in batch search function

### ISSUE THREAD

**Issue by cswbrian** [g0vhk-io/HKAddressParser#38]
If I put more than 5 address, it only loads the first 5 address and pause.

**Comment by wingkwong** [comment]
cannot reproduce. could u provide your testing data?

**Comment by cswbrian** [comment]
I pasted the following 10 addresses
九龍尖沙咀柯士甸道西1號1樓104室
九龍尖沙咀柯士甸道22號九龍公園
九龍油麻地眾坊街60號地下
九龍油麻地海泓道10號
九龍旺角上海街557號旺角綜合大樓2樓
九龍油麻地海庭道6號
九龍大角咀奧海城海輝道11號政府服務中心地下
九龍大角咀櫻桃街18號
九龍大角嘴道148號
九龍大角咀道150號

![123](https://user-images.githubusercontent.com/9110909/49165142-7c76a280-f36b-11e8-8e82-86962d36ffb6.PNG)
It loads only 5 results, and the results are not in the same order as the input

**Comment by wingkwong** [comment]
![screen shot 2018-11-29 at 10 07 27 pm](https://user-images.githubusercontent.com/35857179/49227126-514f8a00-f423-11e8-9dbb-ec9b53da9e5b.png)

It shows 10 results on my machine. 

Google Chrome 70.0.3538.110, MacOS

**Comment by cswbrian** [comment]
@wingkwong Wing, we have got a meetup for the parser this Wednesday (5 Dec) are you free to come?
Location: 1/F, Eaton HK, Yau Ma Tei
Time: 20:00
