### ISSUE TITLE
Warnings on console when doing single search

### ISSUE THREAD

**Issue by nandiheath** [g0vhk-io/HKAddressParser#45]
There is some vuejs warnings when doing single search
```
[Vuetify] v-model has been deprecated
found in

---> <VExpansionPanelContent>
       <VExpansionPanel>
         <SingleMatch> at SingleMatch.vue
           <AddressSearcher> at AddressSearcher.vue
             <VContent>
               <VApp>
                 <App> at App.vue
                   <Root>
```

**Comment by wingkwong** [comment]
Based on [the source](https://github.com/vuetifyjs/vuetify/blob/a99b6a0531711d913395418df3a28b348599e63d/src/components/VExpansionPanel/VExpansionPanelContent.ts#L77), the warning is thrown when there is a value passing as a prop. 

However, [the api guide](https://vuetifyjs.com/en/components/expansion-panels#api) shows that value is still available. Perhaps they are planning for a deprecation. As we need to expand the first one by passing the value to v-expansion-panel-content, we may ignore this warning until the prop has been fully deprecated.

**Comment by nandiheath** [comment]
it seems that there is another way to control the expansion panel. Instead of holding the value at the v-expansion-panel-content, we can hold an array of booleans that indicate the expanded state of each panel content. Hope this will fix the warning.
