### ISSUE TITLE
BatchAddressSearch.vue will become the landing page

### ISSUE THREAD

**Issue by cswbrian** [g0vhk-io/HKAddressParser#62]
https://github.com/g0vhk-io/HKAddressParser/blob/52d11be7c55e8b3cdec160fa0d9d71d670b66167/web/src/pages/BatchAddressSearcher.vue#L93

OBJECTIVE
BatchAddressSearch.vue will become the landing page, and AddressSearch.vue would be deleted. User can input multiple address, and the map can show multiple markers, while only one ResultCard exist.

TODO:
1. Only a single ResultCard will be shown, when user clicks on markers, the info on ResultCard changes.
2. When user clicks on a marker. the marker will pan to the center of map and will be changed to selectedPin
3. Seperate the table to pages/ResultTable.vue

**Comment by wingkwong** [comment]
show ResultCard and ResultTable at the same time?

**Comment by cswbrian** [comment]
or the result table can be separated to another page for clarity

**Comment by wingkwong** [comment]
@cswbrian which branch is the latest one? Didn't see ResultCard in master

**Comment by cswbrian** [comment]
multi-source is the latest one

**Comment by wingkwong** [comment]
BatchAddressSearch.vue the lastest one is in master

this statement is not true. I'll merge it manually.
