### ISSUE TITLE
Numbering the pin corresponding to the row index

### ISSUE THREAD

**Issue by oktak** [g0vhk-io/HKAddressParser#81]
when it is on 地圖模式.

reference:
OpenRice Map
http://www.openrice.com/zh/hongkong/restaurant?mapType=1&toTarget=1&queryString=%7B%22page%22%3A1%2C%22per_page%22%3A500%2C%22mapsearch%22%3A1%2C%22region_id%22%3A0%2C%22normal%22%3A%221%22%2C%22maplat%22%3A22.284321985901634%2C%22maplng%22%3A114.13938500761981%2C%22mapzoom%22%3A16%2C%22wxh%22%3A%221905x839%22%2C%22amenity_id%22%3A%5B%221006%22%5D%2C%22MapTypeId%22%3A%22roadmap%22%7D

Img:
![OpenRice Map](https://user-images.githubusercontent.com/3690205/51222001-afeeaa00-1976-11e9-9809-2da03589e8ea.png)

**Comment by cswbrian** [comment]
Close #100
